
name: CI Pipeline

on:
  push:
    branches: [ main, development, staging ]
  pull_request:
    branches: [ development, staging ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      timeout-minutes: 5
    
    - name: Run linting
      run: npm run lint --if-present
      timeout-minutes: 3
    
    - name: Run tests
      run: npm test --if-present
      timeout-minutes: 5
    
    - name: Build application
      run: npm run build
      timeout-minutes: 8
    
    - name: Detect build output directory
      id: detect-out
      run: |
        if [ -d "./dist" ]; then
          echo "out=dist" >> $GITHUB_OUTPUT
        elif [ -d "./build" ]; then
          echo "out=build" >> $GITHUB_OUTPUT
        else
          echo "::warning::Neither ./dist nor ./build directory found"
          echo "out=dist" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-dist
        path: ${{ steps.detect-out.outputs.out }}
        retention-days: 7
